services:
  postgres:
    image: postgres:16-alpine
    container_name: eventflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: event_ticketing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - eventflow_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d event_ticketing"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  eventflow_pgdata:
