"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { api, formatDate } from "@/lib/api";

type User = {
  id: string; name: string; email: string; role: "ATTENDEE" | "ORGANIZER" | "ADMIN";
  suspendedAt: string | null; suspensionReason: string | null; deletedAt: string | null; createdAt: string;
  _count: { events: number; orders: number; auditLogs: number };
};
type Response = { users: User[]; pagination: { page: number; pageSize: number; total: number; pages: number } };

export default function AdminUsers() {
  const [data, setData] = useState<Response>(); const [query, setQuery] = useState(""); const [role, setRole] = useState(""); const [status, setStatus] = useState("ACTIVE"); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState<string | null>(null);
  async function load() { try { const params = new URLSearchParams({ page: "1", pageSize: "50", status }); if (query.trim()) params.set("q", query.trim()); if (role) params.set("role", role); const response = await api<Response>(`/admin/users?${params.toString()}`); setData(response); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load users."); } }
  useEffect(() => { void load(); }, [role, status]);
  async function manage(user: User, action: "suspend" | "restore" | "delete" | "undelete") { const labels = { suspend: "suspend", restore: "restore", delete: "soft-delete", undelete: "restore from deletion" }; const reason = action === "suspend" ? window.prompt("Suspension reason (optional):", "") : null; if (action === "suspend" && reason === null) return; if (!window.confirm(`${labels[action]} ${user.name}?`)) return; setSaving(user.id); setError(""); setMessage(""); try { await api(`/admin/users/${user.id}`, { method: "PATCH", body: JSON.stringify({ action, ...(action === "suspend" ? { reason } : {}) }) }); setMessage(`${user.name} was ${labels[action]}.`); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to update account."); } finally { setSaving(null); } }
  async function changeRole(user: User, nextRole: User["role"]) { if (nextRole === user.role) return; if (!window.confirm(`Change ${user.name}'s role to ${nextRole}?`)) return; setSaving(user.id); try { await api(`/admin/users/${user.id}`, { method: "PATCH", body: JSON.stringify({ role: nextRole }) }); setMessage(`${user.name}'s role was updated.`); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to update role."); } finally { setSaving(null); } }
  return <main className="container section"><div className="dashboard-head"><div><div className="eyebrow">Administration</div><h1>Manage users</h1><p className="meta">Manage roles, suspension and soft deletion without permanently removing account records.</p></div></div>
    <div className="card" style={{display:"flex",gap:".75rem",flexWrap:"wrap",marginBottom:"1.5rem"}}><input className="input" style={{flex:"1 1 280px"}} placeholder="Search name, email or ID" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void load()}}/><select className="input" style={{maxWidth:200}} value={role} onChange={e=>setRole(e.target.value)}><option value="">All roles</option><option value="ATTENDEE">Attendee</option><option value="ORGANIZER">Organizer</option><option value="ADMIN">Admin</option></select><select className="input" style={{maxWidth:200}} value={status} onChange={e=>setStatus(e.target.value)}><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option><option value="DELETED">Deleted</option><option value="ALL">All accounts</option></select><button className="btn btn-primary" type="button" onClick={()=>void load()}>Search</button></div>
    {message&&<div className="empty" style={{marginBottom:"1rem"}}><p>{message}</p></div>}{error&&<div className="empty" style={{marginBottom:"1rem"}}><h2>Unable to manage users</h2><p>{error}</p></div>}
    <div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Events</th><th>Orders</th><th>Joined</th><th>Actions</th></tr></thead><tbody>{data?.users.map(user=><tr key={user.id}><td><Link href={`/admin/users/${user.id}`}>{user.name}</Link><div className="meta">{user.email}</div></td><td><select className="input" value={user.role} disabled={saving===user.id||!!user.deletedAt} onChange={e=>void changeRole(user,e.target.value as User["role"])}><option value="ATTENDEE">Attendee</option><option value="ORGANIZER">Organizer</option><option value="ADMIN">Admin</option></select></td><td>{user.deletedAt?"DELETED":user.suspendedAt?"SUSPENDED":"ACTIVE"}</td><td>{user._count.events}</td><td>{user._count.orders}</td><td>{formatDate(user.createdAt)}</td><td style={{display:"flex",gap:".4rem",flexWrap:"wrap"}}>{!user.deletedAt&&!user.suspendedAt&&user.role!=="ADMIN"&&<button className="btn btn-secondary" disabled={saving===user.id} onClick={()=>void manage(user,"suspend")}>Suspend</button>}{!user.deletedAt&&user.suspendedAt&&<button className="btn btn-secondary" disabled={saving===user.id} onClick={()=>void manage(user,"restore")}>Unsuspend</button>}{!user.deletedAt&&user.role!=="ADMIN"&&<button className="btn btn-secondary" disabled={saving===user.id} onClick={()=>void manage(user,"delete")}>Delete</button>}{!!user.deletedAt&&<button className="btn btn-secondary" disabled={saving===user.id} onClick={()=>void manage(user,"undelete")}>Restore</button>}</td></tr>)}</tbody></table></div>{data&&<p className="meta" style={{marginTop:"1rem"}}>Showing {data.users.length} of {data.pagination.total} users.</p>}</main>;
}
